### PR TITLE
Bio info

### PR DESCRIPTION
**Pull request by LeoTanoue**

### CODE REVIEW

**Review by travv0 — COMMENTED** [review]
Looks good.  Why's the Forge link in the navbar commented out?

**Comment by travv0** [comment]
Also, did you add me as a reviewer or did it automatically do that when I reviewed it?  Because you should add me when you submit a pull request so I get an email.

**Comment by LeoTanoue** [comment]
I commented out because I don't think we will need that page Phase 1. He doesn't have a standard place of business just yet. 

I need to try again to see if I can find that option

**Comment by travv0** [comment]
@LeoTanoue It's on the right where it says "Reviewers."  You just click the gear to add people.

**Review by travv0 — APPROVED** [review]

**Pull request merged**
